# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudemod < Formula
  desc "Workflow orchestrator for Claude Code that drives incremental feature delivery through structured, multi-phase development workflows."
  homepage "https://github.com/tab58/claudemod"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tab58/claudemod/releases/download/v0.3.0/claudemod_0.3.0_darwin_amd64.tar.gz"
      sha256 "dcb8ecfac3507159f3716ff7c0d92212e4b00f0c1c7e64715e23ef910897bc98"

      define_method(:install) do
        bin.install "claudemod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tab58/claudemod/releases/download/v0.3.0/claudemod_0.3.0_darwin_arm64.tar.gz"
      sha256 "d42cd050cd0a6e61a5090f0280faaed8594224c129e501b256dae082a087b169"

      define_method(:install) do
        bin.install "claudemod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab58/claudemod/releases/download/v0.3.0/claudemod_0.3.0_linux_amd64.tar.gz"
      sha256 "2cee63fae5639f3cfe1130199d6c53aecacb3ec05d09107dbe927c29a828c143"
      define_method(:install) do
        bin.install "claudemod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab58/claudemod/releases/download/v0.3.0/claudemod_0.3.0_linux_arm64.tar.gz"
      sha256 "85ca785f5e28cde444c8bce890bdee30a042100403d9977f5612ee1a97e1cbd3"
      define_method(:install) do
        bin.install "claudemod"
      end
    end
  end

  test do
    system "#{bin}/claudemod", "--version"
  end
end
